### ISSUE TITLE
'module' object has no attribute 'SmartyPants'

### ISSUE THREAD

**Issue by fessacchiotto** [chiehtu/django-misaka#1]
Hi. Just trying to use the package and get this error:

`'module' object has no attribute 'SmartyPants'`

I'm using it in a template:

`<td>{{ row.descrizione| markdown  }}</td> `

Any ideas? TIA

**Comment by chiehtu** [comment]
You got the error because [Misaka](http://misaka.61924.nl/) API has been changed.

They replaced `SmartyPants` [class](https://github.com/FSX/misaka/blob/v1.0.2/src/misaka.pyx#L67) with `smartypants` [function](https://github.com/FSX/misaka/blob/v2.1.0/misaka/api.py#L128).
 
I will fix this soon.

**Comment by chiehtu** [comment]
This issue was fixed in 4f80f6c.
